# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-29 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_userstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='user_id',
            field=models.CharField(default='shreyashshrivastava', max_length=100),
        ),
    ]
