# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-04 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_userstats_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wine_id', models.IntegerField(max_length=100)),
                ('class_id', models.IntegerField(max_length=100)),
            ],
        ),
    ]
