# Generated by Django 2.0 on 2019-05-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_kmeanscentersuser_kmeanscenterswines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kmeanscentersuser',
            name='centers_user',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='kmeanscenterswines',
            name='centers_wines',
            field=models.FloatField(),
        ),
    ]
